# 服务器基础配置
server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8

# 日志管理
logging:
  file:
    path: /Users/wangshjm/tomcat-log
  level:
    org.springframework.security: warn

# spring 基础配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
      username: root
      password: 123456
      #初始连接数
      initial-size: 0
      #最大连接数
      max-active: 20
      #最长等待时间
      max-wait: 60000

  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8
    prefix: classpath:/templates
    suffix: .html
    servlet:
      content-type: text/html

  # 上传文件设置
  servlet:
    multipart:
      max-file-size: 30MB
      enabled: true

  redis:
    host: localhost
    port: 6379

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    messages:
      encoding: UTF-8
    mvc:
      throw-exception-if-no-handler-found: true
    resources:
      add-mappings: false

# 通用mapper配置
mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  identity: MYSQL

# 分页插件
pagehelper:
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
  helper-dialect: mysql

